image: debian:latest

stages:
#  - build
  - update_latest
  - deploy

#create_zip:
#  stage: build
#  script:
#    - echo "Creating zip file"
#    - apt-get update && apt-get install -y zip
#    - zip -r latest.zip contents metadata.json
#  artifacts:
#    paths:
#      - latest.zip
#  only:
#    - main

update_latest_tag:
  stage: update_latest
  script:
    - apt-get update && apt-get install -y git
    - git config --global user.email "eniel160990@gmail.com"
    - git config --global user.name "GitLab CI"
    - git fetch --tags
    - git tag -d latest || true  # Elimina el tag local 'latest' si existe
    - git push --delete origin latest || true  # Elimina el tag remoto 'latest' si existe
    - git tag latest $CI_COMMIT_SHA  # Crea el nuevo tag 'latest' apuntando al último commit
    - git push origin latest  # Sube el tag 'latest' al repositorio remoto
  only:
    - main


release:
  stage: deploy
  script:
    - echo "Releasing"
    - apt-get update && apt-get install -y curl
    - >
      curl --header "Project-ID: $CI_PROJECT_ID" --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" 
      --data "name=Release $CI_COMMIT_TAG" --data "tag_name=$CI_COMMIT_TAG" 
      --data "description=Release of $CI_COMMIT_TAG" 
      "https://www.opencode.net/api/v4/projects/$CI_PROJECT_ID/releases"
  only:
    - main
